import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { AuthModalProvider } from "./context/auth/AuthModalContext";
import AuthModal from "./context/auth/AuthModal";
import Footer from "./components/footer";
import { AuthProvider } from "./context/auth/AuthContext";

import { cookies } from "next/headers";
import I18nProvider from "@/app/i18n/i18nProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "UniLink",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies();
  const allowedLangs = ["en", "hy", "ru"] as const;
  type Lang = typeof allowedLangs[number];

  const rawLang = cookieStore.get("language")?.value;
  const lang: Lang = allowedLangs.includes(rawLang as Lang) ? (rawLang as Lang) : "en";

  return (
    <html
      lang={lang}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`min-h-screen flex flex-col font-normal ${poppins.className}`}>
        <I18nProvider lang={lang}>
          <AuthProvider>
            <AuthModalProvider>
              <Header initialLang={lang} />
              <main className="flex-1">
                {children}
              </main>
              <Footer />
              <AuthModal />
            </AuthModalProvider>
          </AuthProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
